name: Milestone18$(Rev:.r)

pr:
  branches:
    include:
    - develop
    - master
    - release/*
  paths:
    include:
      - '*'
    exclude:
      - 'docs/*'


variables:
 - group: Tokens
 - name: major
   value: 18

 - name: minor
   value: $[counter(variables['major'], 200)]



stages:

#Pull Request Review : Triggered for any PRs
- stage: Review
  condition:  eq(variables['build.Reason'], 'PullRequest')
  dependsOn: []
  jobs:


  - job: BuildCLI
    displayName: 'Build To Validate CLI'
    timeoutInMinutes: 15
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: build_templates/buildcli.yml
        parameters:
         commitToGit: false
         bump: 'prerelease'
         version: 'review'
         publish: false

  - deployment: BuildAzPipelines
    displayName: 'Build and Deploy Azure Pipelines Extension to Review'
    timeoutInMinutes: 40
    pool:
      vmImage: 'windows-latest'
    environment: review
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: false
                stageToDeploy: 'review'
                version: 'review'
                environmentToDeploy: 'review'
                toBuild: true
                organization: dxatscale
                buildNumber: $(minor)

  - job: WaitPluginToInstallonReview
    displayName: 'Wait for  Plugin To Publish on Review'
    dependsOn: BuildAzPipelines
    pool: server
    steps:
      - task: Delay@1
        inputs:
         delayForMinutes: '2'

  - job: InstallExtension
    displayName: 'Install Extension to Review'
    dependsOn: WaitPluginToInstallonReview
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: CmdLine@2
      displayName: 'Login to the org'
      inputs:
            script: |
             echo $(dxatscalereview_extension_pat) | az devops login --org  https://dev.azure.com/dxatscalereview

    - task: CmdLine@2
      displayName: 'Uninstall the extension'
      inputs:
            script: |
             az devops extension uninstall --extension-id sfpowerscripts-review  --publisher-id AzlamSalam --org https://dev.azure.com/dxatscalereview -y

    - task: CmdLine@2
      displayName: 'Install the new version of the plugin'
      inputs:
            script: |
             az devops extension install --extension-id sfpowerscripts-review  --publisher-id AzlamSalam --org https://dev.azure.com/dxatscalereview

    - task: CmdLine@2
      displayName: 'Uninstall the release management extension'
      inputs:
            script: |
             az devops extension uninstall --extension-id sfpowerscripts-release-extension-review  --publisher-id dxatscale --org https://dev.azure.com/dxatscalereview -y

    - task: CmdLine@2
      displayName: 'Install the new version of the release management plugin'
      inputs:
            script: |
             az devops extension install --extension-id sfpowerscripts-release-extension-review  --publisher-id dxatscale --org https://dev.azure.com/dxatscalereview
