name: Milestone17$(Rev:.r)

trigger:
  branches:
    include:
     - release/*
     - develop
  paths:
    exclude:
    - 'docs/*'


variables:
 - group: Tokens
 - name: major
   value: 17

 - name: minor
   value: $[counter(variables['major'], 200)]



stages:

#Merge to Develop, Deploy Alpha builds
- stage: Alpha
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
  dependsOn: []
  jobs:


  - job: BuildCLI
    displayName: sfdx-plugin
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: true
                version: 'alpha'
                publish: true


  - deployment: BuildAzPipelines
    displayName: azpipelines
    timeoutInMinutes: 20
    pool:
      vmImage: 'ubuntu-latest'
    environment: alpha
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: true
                bump: 'prerelease'
                stageToDeploy: 'alpha'
                version: 'alpha'
                environmentToDeploy: 'alpha'
                toBuild: true
                organization: dxatscalereview
                buildNumber: $(minor)


#Beta Stage
- stage: Beta
  condition: and(succeeded('Alpha'),eq(variables['build.sourceBranch'], 'refs/heads/develop'))
  dependsOn: Alpha
  jobs:


  - job: BuildCLI
    displayName: sfdx-plugin
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: false
                version: 'beta'
                publish: false


  - deployment: BuildAzPipelines
    displayName: azpipelines
    timeoutInMinutes: 20
    pool:
      vmImage: 'ubuntu-latest'
    environment: beta
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: false
                bump: 'prerelease'
                stageToDeploy: 'beta'
                version: 'beta'
                environmentToDeploy: 'beta'
                toBuild: true
                organization: dxatscalereview
                buildNumber: $(minor)

# Hotfix stage
- stage: Hotfix
  displayName: Hotfix
  dependsOn: []
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')

  jobs:
  - job: BuildCLI
    displayName: sfdx-plugin
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: false
                version: 'hotfix'
                publish: true


  - deployment: BuildAzPipelines
    displayName: azpipelines
    timeoutInMinutes: 20
    pool:
      vmImage: 'ubuntu-latest'
    environment: hotfix
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: false
                stageToDeploy: 'hotfix'
                version: 'hotfix'
                organization: safebot
                buildNumber: $(minor)

#Prod Stage
- stage: Prod
  condition: or(and(succeeded('Beta'),eq(variables['build.sourceBranch'], 'refs/heads/develop')), and(succeeded('Hotfix'),startsWith(variables['build.sourceBranch'], 'refs/heads/hotfix/')))
  dependsOn:
    - Beta
    - Hotfix
  jobs:


  - job: BuildCLI
    displayName: sfdx-plugin
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: false
                bump: 'patch'
                version: 'latest'
                publish: false


  - deployment: BuildAzPipelines
    displayName: azpipelines
    dependsOn: BuildCLI
    timeoutInMinutes: 30
    pool:
      vmImage: 'ubuntu-latest'
    environment: prod
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: false
                bump: 'patch'
                stageToDeploy: 'prod'
                version: 'prod'
                environmentToDeploy: 'prod'
                toBuild: true
                organization: dxatscalereview
                buildNumber: $(minor)
