name: Milestone17$(Rev:.r)



variables:
 - group: Tokens
 - name: major
   value: 17

 - name: minor
   value: $[counter(variables['major'], 200)]



stages:

- stage: Development
  dependsOn: []
  condition:  eq(variables['build.Reason'], 'Manual')
  jobs:


  - deployment: BuildAzPipelines
    displayName: 'Build and Deploy Azure Pipelines Extension to Develop'
    timeoutInMinutes: 40
    pool:
      vmImage: 'ubuntu-18.04'
    environment: develop
    strategy:
       runOnce:
         deploy:
           steps:

             - template: buildazpipelines.yml
               parameters:
                commitToGit: false
                stageToDeploy: 'dev'
                version: 'dev'
                environmentToDeploy: 'develop'
                toBuild: true
                organization: safebot
                buildNumber: $(minor)

             - task: CmdLine@2
               displayName: 'Login to the org'
               inputs:
                     script: |
                      echo $(safebot_pat) | az devops login --org  https://dev.azure.com/safebot

             - task: CmdLine@2
               displayName: 'Uninstall the extension'
               inputs:
                     script: |
                      az devops extension uninstall --extension-id sfpowerscripts-dev  --publisher-id AzlamSalam --org https://dev.azure.com/safebot -y

             - task: CmdLine@2
               displayName: 'Install the new version of the plugin'
               inputs:
                     script: |
                      az devops extension install --extension-id sfpowerscripts-dev  --publisher-id AzlamSalam --org https://dev.azure.com/safebot