jobs:
- job: InstallNodeModules
  displayName: Install Node Dependencies
  pool:
    vmImage: 'windows-latest'
  
  steps:
    - checkout:  self
  
    - task: Cache@2
      displayName: Cache NPM Modules
      inputs:
       key: 'npm | "$(Agent.OS)" | package-lock.json'
       path: '$(System.DefaultWorkingDirectory)/node_modules'
       cacheHitVar: 'npm | "$(Agent.OS)"'
  
    - task: CmdLine@2
      displayName: Install Node depdencies
      inputs:
        script: 'npm install'
  
    
    - task: CmdLine@2
      inputs:
        script: 'sh ./scripts/get-files-diff.sh'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Detect changes to packages' 
      name: Builddeciderstep
