# Unique name for this workflow
name: review

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - develop

# Jobs to be executed
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
           # Restore Cache
            - name: Resore Cache
              uses: actions/cache@v2.1.3
              with:
                path: |
                   **/node_modules
                   node_modules
                key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}


            - run: npm install
            - run: npx lerna bootstrap
            - run: npx lerna run build
            
                

            # Upload code coverage data
            - name: 'Upload code coverage for Apex to Codecov.io'
              uses: codecov/codecov-action@v1
              with:
                  flags: unittests 
